name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  setup-app:
    name: Setup the app
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install packages
      run: npm install

    - name: Download browsers
      run: npx playwright install
